import type { EquipmentType } from "../types";

/**
 * Katalog över redskap i artistisk gymnastik.
 * widthM/heightM = top-down fotavtryck i meter.
 * physicalHeightM = verklig höjd över golvet (används i 3D-vyn).
 */
export const EQUIPMENT_CATALOG: EquipmentType[] = [
  {
    id: "barr",
    name: "Barr",
    category: "redskap",
    widthM: 3.2,
    heightM: 1.2,
    physicalHeightM: 1.75,
    color: "#A0703F",
    shape: "roundedRect",
    detail: { kind: "parallel-bars" },
    description: "Parallellbarr för herrgymnastik (eller ställbar barr).",
  },
  {
    id: "ojamna-barr",
    name: "Ojämna barr",
    category: "redskap",
    widthM: 2.6,
    heightM: 2.8,
    physicalHeightM: 2.55,
    color: "#8E9AA6",
    shape: "roundedRect",
    detail: { kind: "uneven-bars" },
    description: "Ojämna barr (damgymnastik). Högt räcke 2.55 m, lågt räcke 1.75 m.",
  },
  {
    id: "rack",
    name: "Räck",
    category: "redskap",
    widthM: 2.4,
    heightM: 2.2,
    physicalHeightM: 2.75,
    color: "#8E9AA6",
    shape: "roundedRect",
    detail: { kind: "high-bar" },
    description: "Räckstång.",
  },
  {
    id: "bom",
    name: "Bom",
    category: "redskap",
    widthM: 5.0,
    heightM: 0.4,
    physicalHeightM: 1.25,
    color: "#B5894F",
    shape: "roundedRect",
    detail: { kind: "beam" },
    description: "Balansbom, 5 m.",
  },
  {
    id: "bygelhast",
    name: "Bygelhäst",
    category: "redskap",
    widthM: 1.6,
    heightM: 0.4,
    physicalHeightM: 1.15,
    color: "#8B6B4F",
    shape: "roundedRect",
    detail: { kind: "pommel-horse" },
    description: "Bygelhäst för herrgymnastik.",
  },
  {
    id: "ringar",
    name: "Ringar (med ställning)",
    category: "redskap",
    widthM: 2.4,
    heightM: 2.4,
    physicalHeightM: 2.75,
    color: "#8E4040",
    shape: "roundedRect",
    detail: { kind: "rings" },
    description: "Ringar med ställning. Ringarnas höjd: 2.5 m, ramhöjd: ~5.5 m.",
  },
  {
    id: "ringar-fri",
    name: "Ringar",
    category: "redskap",
    widthM: 0.8,
    heightM: 0.8,
    physicalHeightM: 2.75,
    color: "#8E4040",
    shape: "roundedRect",
    detail: { kind: "rings-free" },
    description: "Ringar utan ställning (hänger i tak/rigg). Ringarnas höjd: 2.75 m.",
  },
  {
    id: "hopp",
    name: "Hoppbord",
    category: "hopp",
    widthM: 0.95,
    heightM: 1.2,
    physicalHeightM: 1.35,
    color: "#CC4E10",
    shape: "roundedRect",
    detail: { kind: "vault" },
    description: "Hoppbord (vault table). 95 cm bredd × 120 cm djup × 135 cm hög.",
  },
  {
    id: "trampett",
    name: "Trampett",
    category: "hopp",
    widthM: 1.15,
    heightM: 1.15,
    physicalHeightM: 0.3,
    color: "#E06020",
    shape: "roundedRect",
    detail: { kind: "trampette" },
    description: "Trampett (studsbräda).",
  },
  {
    id: "minitramp",
    name: "Mini-trampolin",
    category: "hopp",
    widthM: 1.0,
    heightM: 1.0,
    physicalHeightM: 0.3,
    color: "#23293A",
    shape: "roundedRect",
    detail: { kind: "mini-tramp" },
    description: "Mini-trampolin.",
  },
  {
    id: "tumblingbana",
    name: "Tumblingbana",
    category: "matta",
    widthM: 14.0,
    heightM: 2.0,
    physicalHeightM: 0.12,
    color: "#5A8C4A",
    shape: "roundedRect",
    detail: { kind: "tumbling-track" },
    description: "Tumblingbana med fjädrar/skum.",
  },
  {
    id: "airtrack",
    name: "Airtrack",
    category: "matta",
    widthM: 10.0,
    heightM: 2.0,
    physicalHeightM: 0.3,
    color: "#2B8AC6",
    shape: "roundedRect",
    detail: { kind: "air-track" },
    description: "Uppblåsbar airtrack.",
  },
  {
    id: "golv",
    name: "Fristående-matta",
    category: "matta",
    widthM: 12.0,
    heightM: 12.0,
    physicalHeightM: 0.1,
    color: "#A4C7A6",
    shape: "roundedRect",
    detail: { kind: "floor" },
    description: "Fristående-matta 12×12 m.",
  },
  {
    id: "tjockmatta",
    name: "Tjockmatta",
    category: "matta",
    widthM: 3.0,
    heightM: 2.0,
    physicalHeightM: 0.3,
    color: "#4F86C7",
    shape: "roundedRect",
    detail: { kind: "thick-mat" },
    description: "Tjockmatta / nedhoppsmatta.",
  },
  {
    id: "landningsmatta",
    name: "Landningsmatta",
    category: "matta",
    widthM: 2.0,
    heightM: 1.0,
    physicalHeightM: 0.1,
    color: "#D48850",
    shape: "roundedRect",
    detail: { kind: "landing-mat" },
    description: "Landningsmatta.",
  },
  {
    id: "plint",
    name: "Plint",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.4,
    physicalHeightM: 1.2,
    color: "#B7895B",
    shape: "roundedRect",
    detail: { kind: "plinth" },
    description: "Plint.",
  },
  {
    id: "bock",
    name: "Bock",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.35,
    physicalHeightM: 1.0,
    color: "#A47551",
    shape: "roundedRect",
    detail: { kind: "buck" },
    description: "Bock / svingbock.",
  },
  {
    id: "skumgrop",
    name: "Skumgrop",
    category: "tillbehor",
    widthM: 5.0,
    heightM: 3.0,
    physicalHeightM: 0,
    color: "#6E8C5E",
    shape: "roundedRect",
    detail: { kind: "foam-pit" },
    description: "Skumgrop.",
  },
  {
    id: "ribbstol",
    name: "Ribbstol",
    category: "tillbehor",
    widthM: 0.85,
    heightM: 0.25,
    physicalHeightM: 2.4,
    color: "#C8904A",
    shape: "roundedRect",
    detail: { kind: "wall-bars" },
    description: "Ribbstol monterad på vägg. Bredd 85 cm, höjd 240 cm.",
  },
  {
    id: "gymnastibank",
    name: "Gymnastiksätta",
    category: "tillbehor",
    widthM: 3.5,
    heightM: 0.28,
    physicalHeightM: 0.3,
    color: "#D4A84B",
    shape: "roundedRect",
    detail: { kind: "gym-bench" },
    description: "Gymnastiksätta (bänk), 3.5 m lång. Kan lutas mot ribbstol.",
  },
  {
    id: "klatterrep",
    name: "Klätterrep",
    category: "tillbehor",
    widthM: 0.3,
    heightM: 0.3,
    physicalHeightM: 5.0,
    color: "#8B6A3A",
    shape: "roundedRect",
    detail: { kind: "climbing-rope" },
    description: "Klätterrep, hänger i tak/rigg. Ca 5 m.",
  },
];

export const EQUIPMENT_BY_ID: Record<string, EquipmentType> =
  Object.fromEntries(EQUIPMENT_CATALOG.map((e) => [e.id, e]));

/** Extra registry for custom/user-defined equipment types (populated at runtime). */
const _customRegistry: Record<string, EquipmentType> = {};

export function registerEquipmentType(t: EquipmentType): void {
  _customRegistry[t.id] = t;
}

export function unregisterEquipmentType(id: string): void {
  delete _customRegistry[id];
}

/** Look up a type from both the built-in catalog and the custom registry. */
export function getEquipmentById(id: string): EquipmentType | undefined {
  return EQUIPMENT_BY_ID[id] ?? _customRegistry[id];
}

export const CATEGORY_LABELS: Record<string, string> = {
  redskap: "Redskap",
  matta: "Mattor",
  hopp: "Hopp",
  tillbehor: "Tillbehör",
  eget: "Egna redskap",
};
