import type { EquipmentType } from "../types";

/**
 * Katalog över redskap i artistisk gymnastik.
 * Mått är ungefärliga och kan justeras i appen per placering.
 */
export const EQUIPMENT_CATALOG: EquipmentType[] = [
  {
    id: "barr",
    name: "Barr",
    category: "redskap",
    widthM: 3.5,
    heightM: 1.6,
    color: "#F4A261",
    shape: "roundedRect",
    detail: { kind: "parallel-bars" },
    description: "Parallellbarr för herrgymnastik (eller ställbar barr).",
  },
  {
    id: "rack",
    name: "Räck",
    category: "redskap",
    widthM: 2.4,
    heightM: 0.4,
    color: "#9D4EDD",
    shape: "roundedRect",
    detail: { kind: "high-bar" },
    description: "Räckstång.",
  },
  {
    id: "bom",
    name: "Bom",
    category: "redskap",
    widthM: 5.0,
    heightM: 0.2,
    color: "#2A9D8F",
    shape: "roundedRect",
    detail: { kind: "beam" },
    description: "Balansbom, 5 m.",
  },
  {
    id: "bygelhast",
    name: "Bygelhäst",
    category: "redskap",
    widthM: 1.6,
    heightM: 0.4,
    color: "#F08080",
    shape: "roundedRect",
    detail: { kind: "pommel-horse" },
    description: "Bygelhäst för herrgymnastik.",
  },
  {
    id: "ringar",
    name: "Ringar",
    category: "redskap",
    widthM: 0.8,
    heightM: 0.8,
    color: "#8338EC",
    shape: "ellipse",
    detail: { kind: "rings" },
    description: "Ringar (upphängningspunkt).",
  },
  {
    id: "hopp",
    name: "Hoppbord",
    category: "hopp",
    widthM: 1.2,
    heightM: 0.95,
    color: "#FFB703",
    shape: "roundedRect",
    detail: { kind: "vault" },
    description: "Hoppbord för saltohopp.",
  },
  {
    id: "trampett",
    name: "Trampett",
    category: "hopp",
    widthM: 1.15,
    heightM: 1.15,
    color: "#E76F51",
    shape: "roundedRect",
    detail: { kind: "trampette" },
    description: "Trampett (studsbräda).",
  },
  {
    id: "minitramp",
    name: "Mini-trampolin",
    category: "hopp",
    widthM: 1.0,
    heightM: 1.0,
    color: "#FB8500",
    shape: "roundedRect",
    detail: { kind: "mini-tramp" },
    description: "Mini-trampolin.",
  },
  {
    id: "tumblingbana",
    name: "Tumblingbana",
    category: "matta",
    widthM: 14.0,
    heightM: 2.0,
    color: "#80ED99",
    shape: "roundedRect",
    detail: { kind: "tumbling-track" },
    description: "Tumblingbana med fjädrar/skum.",
  },
  {
    id: "airtrack",
    name: "Airtrack",
    category: "matta",
    widthM: 10.0,
    heightM: 2.0,
    color: "#90E0EF",
    shape: "roundedRect",
    detail: { kind: "air-track" },
    description: "Uppblåsbar airtrack.",
  },
  {
    id: "golv",
    name: "Fristående-matta",
    category: "matta",
    widthM: 12.0,
    heightM: 12.0,
    color: "#B5E48C",
    shape: "roundedRect",
    detail: { kind: "floor" },
    description: "Fristående-matta 12×12 m.",
  },
  {
    id: "tjockmatta",
    name: "Tjockmatta",
    category: "matta",
    widthM: 3.0,
    heightM: 2.0,
    color: "#8ECAE6",
    shape: "roundedRect",
    detail: { kind: "thick-mat" },
    description: "Tjockmatta / nedhoppsmatta.",
  },
  {
    id: "landningsmatta",
    name: "Landningsmatta",
    category: "matta",
    widthM: 2.0,
    heightM: 1.0,
    color: "#FFD6A5",
    shape: "roundedRect",
    detail: { kind: "landing-mat" },
    description: "Landningsmatta.",
  },
  {
    id: "plint",
    name: "Plint",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.4,
    color: "#CDB4DB",
    shape: "roundedRect",
    detail: { kind: "plinth" },
    description: "Plint.",
  },
  {
    id: "bock",
    name: "Bock",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.35,
    color: "#BDE0FE",
    shape: "roundedRect",
    detail: { kind: "buck" },
    description: "Bock / svingbock.",
  },
  {
    id: "skumgrop",
    name: "Skumgrop",
    category: "tillbehor",
    widthM: 5.0,
    heightM: 3.0,
    color: "#CAFFBF",
    shape: "roundedRect",
    detail: { kind: "foam-pit" },
    description: "Skumgrop.",
  },
];

export const EQUIPMENT_BY_ID: Record<string, EquipmentType> =
  Object.fromEntries(EQUIPMENT_CATALOG.map((e) => [e.id, e]));

export const CATEGORY_LABELS: Record<string, string> = {
  redskap: "Redskap",
  matta: "Mattor",
  hopp: "Hopp",
  tillbehor: "Tillbehör",
};
