import type { EquipmentType } from "../types";

/**
 * Katalog över redskap i artistisk gymnastik.
 * widthM/heightM = top-down fotavtryck i meter.
 * physicalHeightM = verklig höjd över golvet (används i 3D-vyn).
 */
export const EQUIPMENT_CATALOG: EquipmentType[] = [
  {
    id: "barr",
    name: "Barr",
    category: "redskap",
    widthM: 3.5,
    heightM: 1.7,
    physicalHeightM: 1.95,
    color: "#A0703F",
    shape: "roundedRect",
    detail: { kind: "parallel-bars" },
    description: "Parallellbarr för herrgymnastik (eller ställbar barr).",
  },
  {
    id: "rack",
    name: "Räck",
    category: "redskap",
    widthM: 2.4,
    heightM: 2.2,
    physicalHeightM: 2.75,
    color: "#8E9AA6",
    shape: "roundedRect",
    detail: { kind: "high-bar" },
    description: "Räckstång.",
  },
  {
    id: "bom",
    name: "Bom",
    category: "redskap",
    widthM: 5.0,
    heightM: 0.4,
    physicalHeightM: 1.25,
    color: "#B5894F",
    shape: "roundedRect",
    detail: { kind: "beam" },
    description: "Balansbom, 5 m.",
  },
  {
    id: "bygelhast",
    name: "Bygelhäst",
    category: "redskap",
    widthM: 1.6,
    heightM: 0.4,
    physicalHeightM: 1.15,
    color: "#8B6B4F",
    shape: "roundedRect",
    detail: { kind: "pommel-horse" },
    description: "Bygelhäst för herrgymnastik.",
  },
  {
    id: "ringar",
    name: "Ringar",
    category: "redskap",
    widthM: 1.4,
    heightM: 1.4,
    physicalHeightM: 2.75,
    color: "#E9D9BB",
    shape: "roundedRect",
    detail: { kind: "rings" },
    description: "Ringar (upphängningspunkt).",
  },
  {
    id: "hopp",
    name: "Hoppbord",
    category: "hopp",
    widthM: 1.2,
    heightM: 0.95,
    physicalHeightM: 1.35,
    color: "#8F5C3D",
    shape: "roundedRect",
    detail: { kind: "vault" },
    description: "Hoppbord för saltohopp.",
  },
  {
    id: "trampett",
    name: "Trampett",
    category: "hopp",
    widthM: 1.15,
    heightM: 1.15,
    physicalHeightM: 0.3,
    color: "#2F3542",
    shape: "roundedRect",
    detail: { kind: "trampette" },
    description: "Trampett (studsbräda).",
  },
  {
    id: "minitramp",
    name: "Mini-trampolin",
    category: "hopp",
    widthM: 1.0,
    heightM: 1.0,
    physicalHeightM: 0.3,
    color: "#23293A",
    shape: "roundedRect",
    detail: { kind: "mini-tramp" },
    description: "Mini-trampolin.",
  },
  {
    id: "tumblingbana",
    name: "Tumblingbana",
    category: "matta",
    widthM: 14.0,
    heightM: 2.0,
    physicalHeightM: 0.12,
    color: "#5A8C4A",
    shape: "roundedRect",
    detail: { kind: "tumbling-track" },
    description: "Tumblingbana med fjädrar/skum.",
  },
  {
    id: "airtrack",
    name: "Airtrack",
    category: "matta",
    widthM: 10.0,
    heightM: 2.0,
    physicalHeightM: 0.3,
    color: "#2B8AC6",
    shape: "roundedRect",
    detail: { kind: "air-track" },
    description: "Uppblåsbar airtrack.",
  },
  {
    id: "golv",
    name: "Fristående-matta",
    category: "matta",
    widthM: 12.0,
    heightM: 12.0,
    physicalHeightM: 0.1,
    color: "#A4C7A6",
    shape: "roundedRect",
    detail: { kind: "floor" },
    description: "Fristående-matta 12×12 m.",
  },
  {
    id: "tjockmatta",
    name: "Tjockmatta",
    category: "matta",
    widthM: 3.0,
    heightM: 2.0,
    physicalHeightM: 0.3,
    color: "#4F86C7",
    shape: "roundedRect",
    detail: { kind: "thick-mat" },
    description: "Tjockmatta / nedhoppsmatta.",
  },
  {
    id: "landningsmatta",
    name: "Landningsmatta",
    category: "matta",
    widthM: 2.0,
    heightM: 1.0,
    physicalHeightM: 0.1,
    color: "#D48850",
    shape: "roundedRect",
    detail: { kind: "landing-mat" },
    description: "Landningsmatta.",
  },
  {
    id: "plint",
    name: "Plint",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.4,
    physicalHeightM: 1.2,
    color: "#B7895B",
    shape: "roundedRect",
    detail: { kind: "plinth" },
    description: "Plint.",
  },
  {
    id: "bock",
    name: "Bock",
    category: "tillbehor",
    widthM: 1.0,
    heightM: 0.35,
    physicalHeightM: 1.0,
    color: "#A47551",
    shape: "roundedRect",
    detail: { kind: "buck" },
    description: "Bock / svingbock.",
  },
  {
    id: "skumgrop",
    name: "Skumgrop",
    category: "tillbehor",
    widthM: 5.0,
    heightM: 3.0,
    physicalHeightM: 0,
    color: "#6E8C5E",
    shape: "roundedRect",
    detail: { kind: "foam-pit" },
    description: "Skumgrop.",
  },
];

export const EQUIPMENT_BY_ID: Record<string, EquipmentType> =
  Object.fromEntries(EQUIPMENT_CATALOG.map((e) => [e.id, e]));

export const CATEGORY_LABELS: Record<string, string> = {
  redskap: "Redskap",
  matta: "Mattor",
  hopp: "Hopp",
  tillbehor: "Tillbehör",
};
